# Generated by Django 5.0.3 on 2024-04-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20240415_1737'),
    ]

    operations = [
    ]
