# Generated by Django 5.0.3 on 2024-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_blogpost_product_published_product_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='2024-05-02-16-05-36', unique=True),
        ),
    ]
