# Generated by Django 5.0.3 on 2024-07-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product'), ('can_change_any_description', 'Can change any description'), ('can_change_any_category', 'Can change any category')]},
        ),
    ]
