# Generated by Django 5.0.3 on 2024-10-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_version_product_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
