# Generated by Django 5.0.3 on 2024-10-11 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_announcement_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактная Информация'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='announcement_photos', verbose_name='Добавить фото'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
